apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "network-monitor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
